language: node_js
#node_js:
#  - <version>
#cache: yarn

#install:
#  - yarn install

#script:
#  - yarn test
#  - yarn run build

deploy:
  provider: isa-robot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
