language: node_js
node_js:
  - 12
cache: npm

install:
  - npm install
  - yarn upgrade
  - yarn add yarn

script:
  - npm test
  - npm run build

deploy:
  provider: isa-robot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
