language: node_js
node_js:
  - 12
cache: yarn

install:
#  - npm install
  - yarn install --frozen-lockfile
#  - yarn upgrade
#  - yarn add yarn

script:
#  - npm test
  - yarn test:coverage
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    all_branches: true
#    branch: master
